### ISSUE TITLE
It is trying to install again dbamp even when it is already installed

### ISSUE THREAD

**Issue by RavindraSolanki** [taliesins/cookbook-dbamp#1]
https://github.com/taliesins/cookbook-dbamp/blob/9cd11aebd884d83fee6b9e6155285a195e12c244/recipes/default.rb#L36

The recipe is missing a condition to not run when dbamp is already installed.

**Comment by RavindraSolanki** [comment]
Add the following condition to the code bloc mentioned in the issue does resolve the problem: `not_if {is_dbamp_installed}`

**Comment by taliesins** [comment]
Fixed by #2
